### ISSUE TITLE
Missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by VoyTechnology** [DethRaid/nova-renderer#2]
I know it might be early in the project to have a contribution page, and it's not a requirement, but it might be nice to have a `CONTRIBUTING.md` file with information about how others can contribute. 

While I might not (probably) be of much help myself, there might be others interested and instructions might help :)

**Comment by DethRaid** [comment]
I just accepted a pull request from SylveonBottle to have a CONTRIBUTING.md file
