### ISSUE TITLE
License needs to be defined.

### ISSUE THREAD

**Issue by mdsitton** [DethRaid/nova-renderer#7]
Currently the code has no license specified. Which kinda of makes contributing code... troublesum.

Now depending on how you want this to go you could make everyone that contributes code sign a cla, or just let everyone go free for all(bad thing this way you cant change the license later on unless you get everyone together to agree since). There is a tool to make this simpler if you want to go that route: https://www.clahub.com

But if you just plan on sticking with whatever license you choose permanantly(LGPL/GPL/MIT/BSD) then a cla is probably not needed.

**Comment by phase** [comment]
MIT please.

**Comment by VoyTechnology** [comment]
Not an expert on licences, but please choose something that would allow users to distribute the mod with modpacks. I personally am not the biggest fan of MIT and prefer GPL

**Comment by phase** [comment]
You can't put GPL code with proprietary code. LGPL could work, but MIT is more permissive.

**Comment by Drakulix** [comment]
If you want to go with any license that does not support modpacks you can always add exceptions to it.

**Comment by DethRaid** [comment]
Added MIT license in https://github.com/DethRaid/nova-renderer/commit/fe1a39a904b2b1da76d9b3fe2867278b203cf1c0

**Comment by mdsitton** [comment]
MIT works for me. GPL would probably not have gon well, though technically LGPL could have worked for the nova-lib and some other license for the java code. But a single license is just easier to keep track of i think.
